### ISSUE TITLE
Plate archive request

### ISSUE THREAD

**Issue by ManjarosV** [viniciusbrit/eobard#1]
Yo, pls could you send me the plate file?

**Comment by primevivian** [comment]
I think you can go back on the commits and download it from there. I'm working on a new version but my schedule sucks at the moment. If you need it though I can get the old files and stash them in a folder.

**Comment by primevivian** [comment]
Closed by accident

**Comment by ManjarosV** [comment]
> Closed by accident



> I think you can go back on the commits and download it from there. I'm working on a new version but my schedule sucks at the moment. If you need it though I can get the old files and stash them in a folder.

Ok, thanks for reply.

**Comment by primevivian** [comment]
I should mention that some of the imported symbols and footprints on those files were themselves github repositories that didn't get carried over into this one so you probably have to look for those too.
